/**********************************INSERTS***********************************/
--EJ1
INSERT INTO DEPARTAMENTOS (DEPT_NO,DNOMBRE,LOC) VALUES (55,'RECURSOS','MADRID')
--EJ2
INSERT INTO EMPLEADOS (EMP_NO,APELLIDO,OFICIO,FECHA_ALT,SALARIO,DEPT_NO)
VALUES (8000,'ESCUDERO','EMPLEADO',SYSDATE,1230,55)
--EJ3
INSERT INTO EMPLEADOS 
SELECT 8001,'ROJO',OFICIO,DIR,SYSDATE-1,SALARIO,COMISION,DEPT_NO
FROM EMPLEADOS
WHERE EMP_NO=7654
--EJ4
INSERT INTO EMPLEADOS
SELECT 9050,'CUCALÓN','BECARIO',E1.DIR,NEXT_DAY(SYSDATE,'LUNES'),E2.SALARIO/2,NULL,E1.DEPT_NO
FROM EMPLEADOS E1
JOIN EMPLEADOS E2 ON E2.APELLIDO='ARROYO'
WHERE UPPER(E1.APELLIDO)='SALA'
--EJ5 
INSERT INTO DEPARTAMENTOS 
SELECT 65,'I+D',LOC FROM DEPARTAMENTOS
JOIN EMPLEADOS ON EMPLEADOS.DEPT_NO = DEPARTAMENTOS.DEPT_NO
GROUP BY DEPARTAMENTOS.DEPT_NO, LOC 
HAVING COUNT(*)=
    (SELECT MIN(COUNT(*))
    FROM EMPLEADOS
    GROUP BY DEPT_NO);
--EJ6
INSERT INTO AVERIAS_PARQUE 
SELECT COD_ATRACCION,SYSDATE-1,NULL,NULL,DNI_ENCARGADO
FROM ATRACCIONES JOIN ZONAS ON ATRACCIONES.NOM_ZONA = ZONAS.NOM_ZONA
WHERE UPPER(NOM_ATRACCION)='ENTERRPRISE'
--EJ7
INSERT INTO ATRACCIONES 
SELECT 'A140','Que Miedo',SYSDATE+30,40,NOM_ZONA
FROM ATRACCIONES
GROUP BY NOM_ZONA
HAVING COUNT(*) = (SELECT MIN(COUNT(*)) FROM ATRACCIONES GROUP BY NOM_ZONA);
/**********************************UPDATE***********************************/
--EJ8
UPDATE ALUMNOS SET DIREC ='c/Valbuena 87 1A'
WHERE APENOM LIKE 'Cerrato%'
--EJ9
UPDATE AVERIAS_PARQUE SET COSTE_AVERIA=1200,FECHA_ARREGLO = SYSDATE
WHERE COD_ATRACCION='A100'
--EJ10
UPDATE EMPLE SET COMISION=COMISION+300 
WHERE COMISION IS NULL AND DEPT_NO = (SELECT DEPT_NO FROM DEPART WHERE UPPER(LOC)='BARCELONA')
--EJ11
UPDATE EMPLE SET (OFICIO,SALARIO)=
(SELECT OFICIO,SALARIO FROM EMPLE WHERE UPPER(APELLIDO)='TOVAR')
WHERE UPPER(APELLIDO)='ALONSO'
--EJ12
UPDATE EMPLE SET SALARIO=SALARIO+150
 WHERE TO_CHAR(FECHA_ALT,'YYYY')<2006
--EJ13
UPDATE EMPLE SET SALARIO=SALARIO+100
WHERE SALARIO = (SELECT MIN(SALARIO) FROM EMPLE)
--EJ14
UPDATE EMPLE SET SALARIO=SALARIO+0.10
WHERE SALARIO IN (SELECT MIN(SALARIO) FROM EMPLE GROUP BY OFICIO)
--EJ15
UPDATE EMPLE SET SALARIO = SALARIO+50
WHERE DEPT_NO = (SELECT DEPT_NO FROM DEPART WHERE UPPER(DNOMBRE)='INVESTIGACIÓN') 
AND SALARIO <(SELECT AVG(SALARIO) FROM EMPLE WHERE DEPT_NO = (SELECT DEPT_NO FROM DEPART WHERE UPPER(DNOMBRE)='INVESTIGACIÓN'))
/**********************************DELETE***********************************/
--EJ16
DELETE EMPLE;
--EJ17
DELETE EMPLE WHERE UPPER(OFICIO)='ANALISTA'
--EJ18
DELETE EMPLE WHERE DEPT_NO = (SELECT DEPT_NO FROM DEPART WHERE DNOMBRE='VENTAS')
--EJ19
DELETE EMPLE WHERE DEPT_NO = (SELECT DEPT_NO FROM EMPLE GROUP BY DEPT_NO HAVING COUNT(*) 
                           =(SELECT MIN(COUNT(*)) FROM EMPLE GROUP BY DEPT_NO));
--EJ20
DELETE FROM DEPART WHERE DEPT_NO NOT IN (SELECT DEPART.DEPT_NO FROM DEPART 
                                    JOIN EMPLE ON EMPLE.DEPT_NO = DEPART.DEPT_NO 
                                    GROUP BY DEPART.DEPT_NO
                                    HAVING COUNT(*)>0);
--EJ21
DELETE EMPLE WHERE FECHA_ALT = (SELECT MIN(FECHA_ALT) FROM EMPLE);
--EJ22
DELETE EMPLE E1 WHERE SALARIO < 
                    (SELECT AVG(SALARIO) FROM EMPLE E2 GROUP BY E1.DEPT_NO);