--EJERCICIO 1 CORREGIDO
SELECT CLIENTES_TALLER.Nombre "Nombre del dueño",Count(Fecha_entrada) "VECES EN EL TALLER" ,SUM(Importe)"IMPORTE",Count(Fecha_salida) "ARREGLOS ACABADOS" ,To_number(COUNT(Fecha_entrada)-Count(Fecha_salida))"ARREGLOS SIN TERMINAR"FROM CLIENTES_TALLER
JOIN COCHES_TALLER ON CLIENTES_TALLER.Ncliente = COCHES_TALLER.Ncliente
JOIN ARREGLOS ON COCHES_TALLER.Matricula = ARREGLOS.Matricula
GROUP BY ARREGLOS.Matricula, CLIENTES_TALLER.Nombre
--EJERCICIO 2 CORREGIDO
SELECT Funcion,TO_CHAR(Fecha_ing,'day')"ENTRADA PRIMER EMPLEADO" FROM MECANICOS EXTERNO
where Fecha_ing=(SELECT MIN(Fecha_ing) FROM MECANICOS INTERNO WHERE EXTERNO.Funcion = INTERNO.Funcion);
--EJERCICIO 3 ESTA BIEN
SELECT Funcion "MENOR CANTIDAD EMPLEADOS" FROM MECANICOS
GROUP BY Funcion
HAVING COUNT(*) = (SELECT MIN(COUNT(*)) FROM MECANICOS GROUP BY Funcion);
--EJERCICIO 4 ESTA BIEN
SELECT Matricula "MAS ARREGLOS ACABADOS TIENE" FROM ARREGLOS
group by matricula
having COUNT(Fecha_salida) = (SELECT MAX(COUNT(Fecha_salida)) FROM ARREGLOS GROUP BY MATRICULA);
--EJERCICIO 5 CORREGIDO
SELECT COUNT(*)"MAYOR NUMERO DE ENTRADAS",TO_CHAR(FECHA_ALTA,'YYYY')"AÑO CON MAYOR ENTRADAS" FROM CLIENTES_TALLER
GROUP BY TO_CHAR(FECHA_ALTA,'YYYY')
HAVING COUNT(*) = (SELECT MAX(COUNT(*)) FROM CLIENTES_TALLER GROUP BY TO_CHAR(FECHA_ALTA,'YYYY'));
--EJERCICIO 6 CORREGIDO
SELECT M1.Nombre FROM MECANICOS M1
JOIN ARREGLOS ON M1.NEMPLEADO = ARREGLOS.NEMPLEADO
WHERE UPPER(FUNCION)='CHAPISTA'
GROUP BY M1.Nombre
HAVING COUNT(FECHA_SALIDA) = (SELECT MIN(COUNT(FECHA_SALIDA)) FROM ARREGLOS 
                              JOIN MECANICOS ON ARREGLOS.NEMPxLEADO = MECANICOS.NEMPLEADO
                            WHERE UPPER(FUNCION)='CHAPISTA' GROUP BY ARREGLOS.NEMPLEADO);
--EJERCICIO 7 CORREGIDO
SELECT CLIENTES_TALLER.Nombre "Nombre Cliente" FROM CLIENTES_TALLER
JOIN COCHES_TALLER ON CLIENTES_TALLER.Ncliente = COCHES_TALLER.Ncliente
JOIN ARREGLOS ON COCHES_TALLER.Matricula = ARREGLOS.Matricula
GROUP BY CLIENTES_TALLER.NOMBRE
HAVING SUM(Importe) = (SELECT MAX(SUM(Importe)) FROM ARREGLOS GROUP BY MATRICULA);


--Agrupa por cliente para ver la suma de todos sus importes
SELECT CLIENTES_TALLER.Nombre "Nombre Cliente" FROM CLIENTES_TALLER
JOIN COCHES_TALLER ON CLIENTES_TALLER.Ncliente = COCHES_TALLER.Ncliente
JOIN ARREGLOS ON COCHES_TALLER.Matricula = ARREGLOS.Matricula
GROUP BY CLIENTES_TALLER.NOMBRE
HAVING SUM(Importe) = (SELECT MAX(SUM(Importe)) FROM ARREGLOS
                       JOIN COCHES_TALLER ON ARREGLOS.MATRICULA = COCHES_TALLER.MATRICULA
                       GROUP BY Ncliente);
